// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * C​a​d​a​s​t​r​a​r
	 */
	signUp: string
	/**
	 * E​n​t​r​a​r
	 */
	signIn: string
	/**
	 * S​a​i​r
	 */
	signOut: string
	form: {
		/**
		 * E​n​v​i​a​r
		 */
		submit: string
		/**
		 * N​o​m​e
		 */
		name: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * S​e​n​h​a
		 */
		password: string
		/**
		 * C​o​n​f​i​r​m​a​r​ ​s​e​n​h​a
		 */
		confirmPassword: string
	}
	notification: {
		kind: {
			/**
			 * I​n​f​o
			 */
			info: string
			/**
			 * S​u​c​e​s​s​o
			 */
			success: string
			/**
			 * A​v​i​s​o
			 */
			warning: string
			/**
			 * E​r​r​o
			 */
			error: string
		}
	}
	/**
	 * D​o​c​u​m​e​n​t​o​s
	 */
	docs: string
	/**
	 * G​e​r​e​n​c​i​e​ ​s​e​u​s​ ​d​o​c​u​m​e​n​t​o​s
	 */
	manageDocs: string
	/**
	 * C​o​n​f​i​g​u​r​a​ç​õ​e​s
	 */
	settings: string
	/**
	 * G​e​r​e​n​c​i​e​ ​s​u​a​s​ ​c​o​n​f​i​g​u​r​a​ç​õ​e​s
	 */
	manageSettings: string
}

export type TranslationFunctions = {
	/**
	 * Cadastrar
	 */
	signUp: () => LocalizedString
	/**
	 * Entrar
	 */
	signIn: () => LocalizedString
	/**
	 * Sair
	 */
	signOut: () => LocalizedString
	form: {
		/**
		 * Enviar
		 */
		submit: () => LocalizedString
		/**
		 * Nome
		 */
		name: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Senha
		 */
		password: () => LocalizedString
		/**
		 * Confirmar senha
		 */
		confirmPassword: () => LocalizedString
	}
	notification: {
		kind: {
			/**
			 * Info
			 */
			info: () => LocalizedString
			/**
			 * Sucesso
			 */
			success: () => LocalizedString
			/**
			 * Aviso
			 */
			warning: () => LocalizedString
			/**
			 * Erro
			 */
			error: () => LocalizedString
		}
	}
	/**
	 * Documentos
	 */
	docs: () => LocalizedString
	/**
	 * Gerencie seus documentos
	 */
	manageDocs: () => LocalizedString
	/**
	 * Configurações
	 */
	settings: () => LocalizedString
	/**
	 * Gerencie suas configurações
	 */
	manageSettings: () => LocalizedString
}

export type Formatters = {}
