// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'pt'

export type Locales =
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	form: {
		/**
		 * E​n​v​i​a​r
		 */
		submit: string
	}
	notification: {
		kind: {
			/**
			 * I​n​f​o
			 */
			info: string
			/**
			 * S​u​c​e​s​s​o
			 */
			success: string
			/**
			 * A​v​i​s​o
			 */
			warning: string
			/**
			 * E​r​r​o
			 */
			error: string
		}
	}
}

export type TranslationFunctions = {
	form: {
		/**
		 * Enviar
		 */
		submit: () => LocalizedString
	}
	notification: {
		kind: {
			/**
			 * Info
			 */
			info: () => LocalizedString
			/**
			 * Sucesso
			 */
			success: () => LocalizedString
			/**
			 * Aviso
			 */
			warning: () => LocalizedString
			/**
			 * Erro
			 */
			error: () => LocalizedString
		}
	}
}

export type Formatters = {}
